SELECT COUNT(*)  
FROM PRODUCT_MAST;  


SELECT COMPANY, COUNT(*)  
FROM PRODUCT_MAST  
GROUP BY COMPANY;  

SELECT COMPANY, COUNT(*)  
FROM PRODUCT_MAST  
GROUP BY COMPANY  
HAVING COUNT(*)>2;  


SELECT SUM(COST)  
FROM PRODUCT_MAST;  

SELECT SUM(COST)  
FROM PRODUCT_MAST  
WHERE QTY>3;  

SELECT SUM(COST)  
FROM PRODUCT_MAST  
WHERE QTY>3  
GROUP BY COMPANY;  

SELECT COMPANY, SUM(COST)  
FROM PRODUCT_MAST  
GROUP BY COMPANY  
HAVING SUM(COST)>=170;  

SELECT AVG(COST)  
FROM PRODUCT_MAST;  

SELECT MAX(RATE)  
FROM PRODUCT_MAST;  

SELECT MIN(RATE)  
FROM PRODUCT_MAST; 